Handle error when message file cannot be read

diff --git a/templates/hooks/commit-msg b/templates/hooks/commit-msg
--- a/templates/hooks/commit-msg
+++ b/templates/hooks/commit-msg
@@ -14,14 +14,24 @@ if [ -z "$COMMIT_MESSAGE_PATH" ]; then
   >&2 echo "fit-commit: WARNING: Skipping checks because the Git hook was not passed the"
   >&2 echo "fit-commit: commit message file path. This is usually \`.git/COMMIT_EDITMSG\`."
   >&2 echo "fit-commit: This hook was called via: $0 $*"
-  >&2 echo "fit-commit: Please submit a bug report with the project."
+  >&2 echo "fit-commit: Please submit a bug report with the project:"
+  >&2 echo "fit-commit: https://github.com/m1foley/fit-commit/issues"
+  exit 0
+fi
+if [ ! -r "$COMMIT_MESSAGE_PATH" ]; then
+  >&2 echo "fit-commit: WARNING: Skipping checks because the commit message file cannot be read:"
+  >&2 echo "fit-commit: $COMMIT_MESSAGE_PATH"
+  >&2 echo "fit-commit: This hook was called via: $0 $*"
+  >&2 echo "fit-commit: Please submit a bug report with the project:"
+  >&2 echo "fit-commit: https://github.com/m1foley/fit-commit/issues"
   exit 0
 fi
 
 export GIT_BRANCH_NAME=`git name-rev --name-only HEAD`
 if [ -z "$GIT_BRANCH_NAME" ]; then
   >&2 echo "fit-commit: WARNING: Skipping checks because the Git branch cannot be determined."
-  >&2 echo "fit-commit: Please submit a bug report with the project."
+  >&2 echo "fit-commit: Please submit a bug report with the project:"
+  >&2 echo "fit-commit: https://github.com/m1foley/fit-commit/issues"
   exit 0
 fi
 
